[tox]
envlist = py312-django{42},quality,without-django
requires = tox-uv>=1
skip_missing_interpreters = True

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    django42: django42
commands = pytest -v --disable-pytest-warnings --nomigrations {posargs}

[testenv:without-django]
runner = uv-venv-lock-runner
dependency_groups = test
commands = pytest --disable-pytest-warnings --ignore=src/opaque_keys/edx/django {posargs}

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    pycodestyle --config=.pep8 src/opaque_keys
    mypy
    pylint --rcfile=pylintrc src/opaque_keys

[testenv:docs]
runner = uv-venv-lock-runner
dependency_groups = doc
allowlist_externals =
    make
    env
setenv =
    SPHINXOPTS = -W
commands =
    make -e -C docs clean
    make -e -C docs html
