name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12']
        toxenv: [quality, docs, without-django, django42]

    steps:
    - uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: make requirements

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox -- --hypothesis-profile=ci

    - name: Run Coverage
      if: matrix.python-version == '3.11' && matrix.toxenv == 'django42'
      uses: codecov/codecov-action@v5
      with:
        flags: unittests
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
